export const FETCH_STUFF = "FETCH_STUFF";

export const RECEIVE_STUFF = "RECEIVE_STUFF";

export const FETCH_FARMER = "FETCH_FARMER";

export const RECEIVE_FARMER = "RECEIVE_FARMER";

export const ADD_FARMER = "ADD_FARMER";

export const RECEIVE_AGREEMENT = "RECEIVE_AGREEMENT";

export const SHOW_AGREEMENT = "SHOW_AGREEMENT";

export const SHOW_FARMER = "SHOW_FARMER";

export const ADD_AGREEMENT = "ADD_AGREEMENT";

export const RECEIVE_DELIVERIES = "RECEIVE_DELIVERIES";

export const SHOW_DELIVERY = "SHOW_DELIVERY";

export const ADD_DELIVERY = "ADD_DELIVERY";
	
export const RECEIVE_EXPORTS_ENTITIES = "RECEIVE_EXPORTS_ENTITIES";

export const SHOW_EXPORTS_ENTITY = "SHOW_EXPORTS_ENTITY";

export const ADD_EXPORTS_ENTITY = "ADD_EXPORTS_ENTITY";

export const RECEIVE_EXPORTS = "RECEIVE_EXPORTS";

export const SHOW_EXPORTS = "SHOW_EXPORTS";

export const ADD_EXPORTS = "ADD_EXPORTS";

export const RECEIVE_SUPPLY = "RECEIVE_SUPPLY";

export const SHOW_SUPPLY = "SHOW_SUPPLY";

export const ADD_SUPPLY = "ADD_SUPPLY";
