export const FETCH_STUFF = "FETCH_STUFF";

export const RECEIVE_STUFF = "RECEIVE_STUFF";

export const FETCH_FARMER = "FETCH_FARMER";

export const RECEIVE_FARMER = "RECEIVE_FARMER";

export const ADD_FARMER = "ADD_FARMER";

export const RECEIVE_AGREEMENT = "RECEIVE_AGREEMENT";